#!/usr/bin/env python3
"""Verify that the generated Chinese font subsets really cover the UI text.

Compiling a font and shipping Chinese strings proves nothing about what appears
on screen: UTF-8 source and a successful build are both compatible with a screen
full of placeholder boxes. This check closes that gap by reading the *generated*
font tables (the same data the linker puts in Flash) and confirming every code
point the application can display is present.

It also asserts a known-absent code point is reported as missing, so the test
cannot pass vacuously if the table parser silently returns an empty set.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "assets" / "fonts"

# tools/gen_fonts.py is imported as the policy source of truth; do not leave a
# __pycache__ directory behind in the repository when this test is run directly.
sys.dont_write_bytecode = True
sys.path.insert(0, str(ROOT / "tools"))
import gen_fonts  # noqa: E402  (repository tool used as the policy source of truth)

# A code point that no CJK subset generated by this project should contain: it is
# an uncommon CJK Extension B character. Used as the negative control.
KNOWN_MISSING = 0x20000

CMAP_RE = re.compile(
    r"\.range_start = (\d+), \.range_length = (\d+), \.glyph_id_start = (\d+),\s*"
    r"\.unicode_list = (\w+), \.glyph_id_ofs_list = (\w+), \.list_length = (\d+)"
)
LIST_RE_TEMPLATE = r"static const uint16_t {name}\[\] = \{{(.*?)\}};"


def parse_covered(path: Path) -> set[int]:
    """Extract every code point the generated font can render."""
    text = path.read_text(encoding="utf-8")

    lists: dict[str, list[int]] = {}
    for name, body in re.findall(r"static const uint16_t (unicode_list_\d+)\[\] = \{(.*?)\};",
                                 text, re.S):
        lists[name] = [int(token, 16) for token in re.findall(r"0x[0-9a-fA-F]+", body)]

    covered: set[int] = set()
    for start, length, _gid, ulist, _ofs, list_len in CMAP_RE.findall(text):
        start = int(start)
        length = int(length)
        if ulist == "NULL":
            # Dense range: every code point in [start, start + length) exists.
            covered.update(range(start, start + length))
            continue
        offsets = lists.get(ulist)
        assert offsets is not None, f"{path.name}: cmap references missing {ulist}"
        assert len(offsets) == int(list_len), (
            f"{path.name}: {ulist} has {len(offsets)} entries, cmap says {list_len}"
        )
        covered.update(start + offset for offset in offsets)
    return covered


def check_font(name: str, required: set[int]) -> int:
    path = FONT_DIR / f"{name}.c"
    assert path.is_file(), f"missing generated font: {path}"
    text = path.read_text(encoding="utf-8", errors="replace")
    assert f"const lv_font_t {name} " in text, f"{path.name}: symbol {name} not defined"

    covered = parse_covered(path)
    assert covered, f"{path.name}: parsed an empty coverage set (parser broken?)"

    # Negative control: the parser must be able to report a missing code point.
    assert KNOWN_MISSING not in covered, (
        f"{path.name}: negative control U+{KNOWN_MISSING:04X} reported as covered"
    )

    missing = sorted(required - covered)
    if missing:
        preview = ", ".join(f"U+{cp:04X}" for cp in missing[:20])
        raise AssertionError(
            f"{path.name}: {len(missing)} required code point(s) are not in the font: {preview}"
        )
    return len(covered)


def expect_missing(name: str, code_point: int) -> None:
    """Assert the font genuinely lacks a code point (keeps the check honest)."""
    path = FONT_DIR / f"{name}.c"
    covered = parse_covered(path)
    assert code_point not in covered, (
        f"{path.name}: expected U+{code_point:04X} to be absent, but it is covered"
    )


def main() -> int:
    literal_cps, all_cps = gen_fonts.scan_sources()
    assert literal_cps, "no string literals found in main/; source scanning is broken"

    base = gen_fonts.base_codepoints()

    # Two tiers, because they mean different things:
    #   MUST  - code points the application can actually put on a label: every
    #           string literal in main/ plus printable ASCII. Missing one of these
    #           is a visible defect, so it fails the check.
    #   BEST  - the broad CJK baseline requested for dynamic text (an SSID, an ICY
    #           title). The source font is itself a subset and simply has no glyph
    #           for many punctuation code points in those blocks, so this tier is
    #           reported as a ratio with a floor instead of a hard requirement.
    required = gen_fonts.filter_displayable(literal_cps | set(range(0x20, 0x7F)))
    assert required, "no string literals found in main/; source scanning is broken"

    covered_16 = check_font("radio_font_cjk_16", required)

    baseline = gen_fonts.filter_displayable(
        base | gen_fonts.gb2312_codepoints() | gen_fonts.big5_level1_codepoints()
    )
    b16 = parse_covered(FONT_DIR / "radio_font_cjk_16.c")
    hit = len(baseline & b16)
    ratio = hit / len(baseline)
    print(f"CJK baseline coverage       : {hit}/{len(baseline)} ({ratio:.1%})")
    assert ratio > 0.80, f"CJK baseline coverage regressed to {ratio:.1%}"
    # Guard against a catastrophic regression (e.g. an empty or truncated table).
    assert covered_16 > 4000, f"16 px font only covers {covered_16} code points"

    # The whole CJK ideograph block must be present: the fallback font exists for
    # dynamic text (an SSID, an ICY title), which is not limited to common
    # characters. Spot-check a handful of uncommon but *assigned* ones so a
    # "common subset" regression cannot slip through. (U+9FFF is unassigned in
    # Unicode, so it is deliberately not in this list.)
    for cp in (0x4E00, 0x5B57, 0x8B1B, 0x9F98, 0x9F9C, 0x9FA5):
        assert cp in b16, f"CJK block coverage lost U+{cp:04X}"

    # ASCII must work: the UI is English.
    for cp in (0x20, 0x41, 0x61, 0x30, 0x25, 0x2E, 0x2D):
        assert cp in b16, f"radio_font_cjk_16: missing ASCII U+{cp:04X}"

    # The UI itself is English, but dynamic text can still be Chinese: a Wi-Fi
    # SSID, an ICY stream title, or an imported station name. Assert the fallback
    # is real rather than assumed, so "English UI with CJK support" is a checked
    # claim.
    for ch in "电台音乐新闻香港新加坡马来西亚设置收藏音量":
        assert ord(ch) in b16, f"CJK fallback lost U+{ord(ch):04X} ({ch})"

    expect_missing("radio_font_cjk_16", KNOWN_MISSING)

    print(f"radio_font_cjk_16 covers {len(required)} required code points "
          f"({covered_16} glyphs in table)")
    print("Font coverage: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
